AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorld:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: python3.6
      Handler: lambda/bots.lambda_handler
      Policies: AmazonDynamoDBFullAccess
      Events:
        Index:
          Type: Api
          Properties:
            Path: /api/v1/bots
            Method: get
