AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FiZZ Lambda API
Resources:
  Accounts:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/accounts
      Handler: accounts/accounts.handler
      Runtime: python3.6
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetCredentials:
          Type: Api
          Properties:
            Path: /api/v1/accounts/credentials
            Method: get
        GetAccount:
          Type: Api
          Properties:
            Path: /api/v1/accounts/{username}
            Method: get
        GetAccountBots:
          Type: Api
          Properties:
            Path: /api/v1/accounts/{username}
            Method: get

  Games:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/games
      Handler: games/games.handler
      Runtime: python3.6
      Policies: AmazonDynamoDBFullAccess
      Events:
        RunMatch:
          Type: Api
          Properties:
            Path: /api/v1/games/{gameName}/match
            Method: post
        FinishMatch:
          Type: Api
          Properties:
            Path: /api/v1/games/{gameName}/finish
            Method: post
        GetRanking:
          Type: Api
          Properties:
            Path: /api/v1/games/{gameName}/ranking
            Method: get

  Bots:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/bots
      Handler: bots/bots.handler
      Runtime: python3.6
      Policies: AmazonDynamoDBFullAccess
      Events:
        ScanBots:
          Type: Api
          Properties:
            Path: /api/v1/bots
            Method: get
        GetBot:
          Type: Api
          Properties:
            Path: /api/v1/bots/{botId}
            Method: get
        CreateBot:
          Type: Api
          Properties:
            Path: /api/v1/bots/{gameName}
            Method: post
        UpdateBot:
          Type: Api
          Properties:
            Path: /api/v1/bots/{botId}
            Method: put

  Results:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/results
      Handler: results/results.handler
      Runtime: python3.6
      Policies: AmazonDynamoDBFullAccess
      Events:
        ScanResults:
          Type: Api
          Properties:
            Path: /api/v1/matches
            Method: get
        GetResult:
          Type: Api
          Properties:
            Path: /api/v1/matches/{resultId}
            Method: get
        GetFightsLog:
          Type: Api
          Properties:
            Path: /api/v1/matches/{resultId}/{ext}
            Method: put

  Auth:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/auth
      Handler: auth/auth.handler
      Runtime: python3.6
      Events:
        Login:
          Type: Api
          Properties:
            Path: /api/v1/auth/login
            Method: post
        SignUp:
          Type: Api
          Properties:
            Path: /api/v1/auth/signup
            Method: post
        Session:
          Type: Api
          Properties:
            Path: /api/v1/auth/session
            Method: get
