import api from '../api';

export const ACCOUNTS_GET_CREDENTIALS = 'ACCOUNTS_GET_CREDENTIALS';
export const ACCOUNTS_GET_CREDENTIALS_REQUEST = 'ACCOUNTS_GET_CREDENTIALS_REQUEST';
export const ACCOUNTS_GET_CREDENTIALS_SUCCESS = 'ACCOUNTS_GET_CREDENTIALS_SUCCESS';
export const ACCOUNTS_GET_CREDENTIALS_FAIL = 'ACCOUNTS_GET_CREDENTIALS_FAIL';

export const ACCOUNTS_GET_ACCOUNT = 'ACCOUNTS_GET_ACCOUNT';
export const ACCOUNTS_GET_ACCOUNT_REQUEST = 'ACCOUNTS_GET_ACCOUNT_REQUEST';
export const ACCOUNTS_GET_ACCOUNT_SUCCESS = 'ACCOUNTS_GET_ACCOUNT_SUCCESS';
export const ACCOUNTS_GET_ACCOUNT_FAIL = 'ACCOUNTS_GET_ACCOUNT_FAIL';

export const ACCOUNTS_GET_ACCOUNT_BOTS = 'ACCOUNTS_GET_ACCOUNT_BOTS';
export const ACCOUNTS_GET_ACCOUNT_BOTS_REQUEST = 'ACCOUNTS_GET_ACCOUNT_BOTS_REQUEST';
export const ACCOUNTS_GET_ACCOUNT_BOTS_SUCCESS = 'ACCOUNTS_GET_ACCOUNT_BOTS_SUCCESS';
export const ACCOUNTS_GET_ACCOUNT_BOTS_FAIL = 'ACCOUNTS_GET_ACCOUNT_BOTS_FAIL';
