import api from '../api';

export const MATCHES_GET_HISTORY = 'MATCHES_GET_HISTORY';
export const MATCHES_GET_HISTORY_REQUEST = 'MATCHES_GET_HISTORY_REQUEST';
export const MATCHES_GET_HISTORY_SUCCESS = 'MATCHES_GET_HISTORY_SUCCESS';
export const MATCHES_GET_HISTORY_FAIL = 'MATCHES_GET_HISTORY_FAIL';

export const MATCHES_GET_RESULT = 'MATCHES_GET_RESULT';
export const MATCHES_GET_RESULT_REQUEST = 'MATCHES_GET_RESULT_REQUEST';
export const MATCHES_GET_RESULT_SUCCESS = 'MATCHES_GET_RESULT_SUCCESS';
export const MATCHES_GET_RESULT_FAIL = 'MATCHES_GET_RESULT_FAIL';

export const MATCHES_GET_FIGHTS_LOG = 'MATCHES_GET_FIGHTS_LOG';
export const MATCHES_GET_FIGHTS_LOG_REQUEST = 'MATCHES_GET_FIGHTS_LOG_REQUEST';
export const MATCHES_GET_FIGHTS_LOG_SUCCESS = 'MATCHES_GET_FIGHTS_LOG_SUCCESS';
export const MATCHES_GET_FIGHTS_LOG_FAIL = 'MATCHES_GET_FIGHTS_LOG_FAIL';
